In [170]:
import numpy as np
import pandas as pd

In [171]:
fifa = pd.read_csv("/Users/zakeerahmedshaik/Downloads/Fifa 23 Players Data.csv")
fifa.head()

Known As           Full Name  Overall  Potential  Value(in Euro)  \
0        L. Messi        Lionel Messi       91         91        54000000   
1      K. Benzema       Karim Benzema       91         91        64000000   
2  R. Lewandowski  Robert Lewandowski       91         91        84000000   
3    K. De Bruyne     Kevin De Bruyne       91         91       107500000   
4       K. Mbappé       Kylian Mbappé       91         95       190500000   

  Positions Played Best Position Nationality  \
0               RW           CAM   Argentina   
1            CF,ST            CF      France   
2               ST            ST      Poland   
3           CM,CAM            CM     Belgium   
4            ST,LW            ST      France   

                                         Image Link  Age  ...  LM Rating  \
0  https://cdn.sofifa.net/players/158/023/23_60.png   35  ...         91   
1  https://cdn.sofifa.net/players/165/153/23_60.png   34  ...         89   
2  https://cdn.sofifa.net/players/188/545/23_60.png   33  ...         86   
3  https://cdn.sofifa.net/players/192/985/23_60.png   31  ...         91   
4  https://cdn.sofifa.net/players/231/747/23_60.png   23  ...         92   

   CM Rating  RM Rating  LWB Rating CDM Rating  RWB Rating  LB Rating  \
0         88         91          67         66          67         62   
1         84         89          67         67          67         63   
2         83         86          67         69          67         64   
3         91         91          82         82          82         78   
4         84         92          70         66          70         66   

  CB Rating RB Rating GK Rating  
0        53        62        22  
1        58        63        21  
2        63        64        22  
3        72        78        24  
4        57        66        21  

[5 rows x 89 columns]

In [172]:
fifa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18539 entries, 0 to 18538
Data columns (total 89 columns):
 #   Column                       Non-Null Count  Dtype 
---  ------                       --------------  ----- 
 0   Known As                     18539 non-null  object
 1   Full Name                    18539 non-null  object
 2   Overall                      18539 non-null  int64 
 3   Potential                    18539 non-null  int64 
 4   Value(in Euro)               18539 non-null  int64 
 5   Positions Played             18539 non-null  object
 6   Best Position                18539 non-null  object
 7   Nationality                  18539 non-null  object
 8   Image Link                   18539 non-null  object
 9   Age                          18539 non-null  int64 
 10  Height(in cm)                18539 non-null  int64 
 11  Weight(in kg)                18539 non-null  int64 
 12  TotalStats                   18539 non-null  int64 
 13  BaseStats                    18

In [173]:
fifa.dropna(axis=0, inplace=True)

# pandas specific issue - why you might want to reset the index
# housing.reset_index(inplace=True, drop=True)

fifa.describe()
fifa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18539 entries, 0 to 18538
Data columns (total 89 columns):
 #   Column                       Non-Null Count  Dtype 
---  ------                       --------------  ----- 
 0   Known As                     18539 non-null  object
 1   Full Name                    18539 non-null  object
 2   Overall                      18539 non-null  int64 
 3   Potential                    18539 non-null  int64 
 4   Value(in Euro)               18539 non-null  int64 
 5   Positions Played             18539 non-null  object
 6   Best Position                18539 non-null  object
 7   Nationality                  18539 non-null  object
 8   Image Link                   18539 non-null  object
 9   Age                          18539 non-null  int64 
 10  Height(in cm)                18539 non-null  int64 
 11  Weight(in kg)                18539 non-null  int64 
 12  TotalStats                   18539 non-null  int64 
 13  BaseStats                    18

# creating 3 differernt target variables

In [174]:
actual_ratings=fifa["Overall"]
actual_wage=fifa["Wage(in Euro)"]


In [175]:
actual_value=fifa["Value(in Euro)"]

In [176]:
actual_ratings[:10]

0    91
1    91
2    91
3    91
4    91
5    90
6    90
7    90
8    90
9    90
Name: Overall, dtype: int64

# creating independent variables

In [177]:
fifa_necc= fifa.drop(["Known As",
                     "Full Name",
                     "Potential",
                      "Overall",
                     "Value(in Euro)"
                     ,"Positions Played",
                     "Nationality",
                     "Image Link",
                     "Club Name",
                    "Wage(in Euro)",
                    "Release Clause",
                    "Club Position",
                    "Contract Until",
                    "Club Jersey Number","Joined On","On Loan","International Reputation",
                     "National Team Name","National Team Image Link","National Team Position","National Team Jersey Number"],axis=1)

In [178]:
fifa_necc

Best Position  Age  Height(in cm)  Weight(in kg)  TotalStats  BaseStats  \
0               CAM   35            169             67        2190        452   
1                CF   34            185             81        2147        455   
2                ST   33            185             81        2205        458   
3                CM   31            181             70        2303        483   
4                ST   23            182             73        2177        470   
...             ...  ...            ...            ...         ...        ...   
18534           CAM   21            174             68        1287        274   
18535           CDM   17            175             60        1289        267   
18536            RM   18            170             65        1333        277   
18537            CB   17            178             65        1113        226   
18538            LB   25            176             66        1277        269   

      Preferred Foot  Weak Foot Rating  Skill Moves Attacking Work Rate  ...  \
0               Left                 4            4                 Low  ...   
1              Right                 4            4              Medium  ...   
2              Right                 4            4                High  ...   
3              Right                 5            4                High  ...   
4              Right                 4            5                High  ...   
...              ...               ...          ...                 ...  ...   
18534          Right                 3            2              Medium  ...   
18535          Right                 3            2              Medium  ...   
18536          Right                 3            2                High  ...   
18537          Right                 3            2              Medium  ...   
18538           Left                 3            2              Medium  ...   

      LM Rating  CM Rating  RM Rating  LWB Rating  CDM Rating  RWB Rating  \
0            91         88         91          67          66          67   
1            89         84         89          67          67          67   
2            86         83         86          67          69          67   
3            91         91         91          82          82          82   
4            92         84         92          70          66          70   
...         ...        ...        ...         ...         ...         ...   
18534        50         44         50          41          38          41   
18535        45         45         45          47          48          47   
18536        52         49         52          46          44          46   
18537        33         33         33          44          42          44   
18538        44         40         44          46          43          46   

       LB Rating  CB Rating  RB Rating  GK Rating  
0             62         53         62         22  
1             63         58         63         21  
2             64         63         64         22  
3             78         72         78         24  
4             66         57         66         21  
...          ...        ...        ...        ...  
18534         40         36         40         15  
18535         49         49         49         15  
18536         46         42         46         17  
18537         47         49         47         15  
18538         47         47         47         19  

[18539 rows x 68 columns]

# Considering only numeric variables

In [179]:
fifa_necc_num= fifa_necc.drop(["Best Position","Preferred Foot","Attacking Work Rate","Defensive Work Rate"],axis=1)

In [180]:
fifa_necc_num.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18539 entries, 0 to 18538
Data columns (total 64 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Age                     18539 non-null  int64
 1   Height(in cm)           18539 non-null  int64
 2   Weight(in kg)           18539 non-null  int64
 3   TotalStats              18539 non-null  int64
 4   BaseStats               18539 non-null  int64
 5   Weak Foot Rating        18539 non-null  int64
 6   Skill Moves             18539 non-null  int64
 7   Pace Total              18539 non-null  int64
 8   Shooting Total          18539 non-null  int64
 9   Passing Total           18539 non-null  int64
 10  Dribbling Total         18539 non-null  int64
 11  Defending Total         18539 non-null  int64
 12  Physicality Total       18539 non-null  int64
 13  Crossing                18539 non-null  int64
 14  Finishing               18539 non-null  int64
 15  Heading Accuracy   

In [181]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

fifa_standard = scaler.fit_transform(fifa_necc_num)

In [182]:
fifa_standard

array([[ 2.06857036, -1.83012546, -1.16546879, ..., -0.10365114,
         0.44845764, -0.08320695],
       [ 1.85661773,  0.50294629,  0.83070877, ...,  0.23548064,
         0.51908368, -0.14939478],
       [ 1.64466509,  0.50294629,  0.83070877, ...,  0.57461243,
         0.58970971, -0.08320695],
       ...,
       [-1.53462442, -1.68430847, -1.45063701, ..., -0.84974108,
        -0.681559  , -0.41414611],
       [-1.74657705, -0.5177726 , -1.45063701, ..., -0.37495657,
        -0.61093296, -0.54652178],
       [-0.05095598, -0.80940657, -1.3080529 , ..., -0.51060929,
        -0.61093296, -0.28177045]])

# Test Train for pred of ratings

In [227]:
from sklearn.model_selection import train_test_split

train_x, test_x, train_y_R, test_y_R = train_test_split(fifa_necc_num, actual_ratings, test_size=0.3)

In [221]:
train_x, test_x, train_y_R, test_y_R = train_test_split(fifa_necc_num, actual_value, test_size=0.3)

In [228]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score


model = LinearRegression()
model.fit(train_x, train_y_R)
pred_R = model.predict(test_x)


pred_R[:5]

array([71.22497492, 61.2140821 , 60.17730478, 61.5383622 , 61.99162224])

In [229]:
print(sm.mean_absolute_error(test_y_R, pred_R))


1.5584106524316212


In [184]:
train_y_R[:5]

2421     73
11498    64
9024     66
2262     74
998      77
Name: Overall, dtype: int64

In [185]:

from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score


model = LinearRegression()
model.fit(train_x, train_y_R)
pred_R = model.predict(test_x)


pred_R[:5]


array([62.37170987, 64.39630433, 63.66558091, 65.09738448, 63.95898034])

In [186]:
#Computed the r2 score
print(sm.mean_absolute_error(test_y_R, pred_R))


1.5623958326818992


In [187]:
test_y_R[:5]

11025    64
15856    59
9405     66
12629    63
10520    65
Name: Overall, dtype: int64

In [188]:
type(pred_R)

numpy.ndarray

# Creating data frame for predicted values of Rating for full data set

In [189]:
pip2_inp=model.predict(fifa_necc_num)

In [190]:
len(pip2_inp)

18539

In [191]:
pip2_inp_df= pd.DataFrame(pip2_inp)

In [192]:
pip2_inp_df.rename(columns={0:'Predicted_ratings'},inplace=True)

In [193]:
pip2_inp_df

Predicted_ratings
0              88.444981
1              91.547345
2              90.695964
3              88.536642
4              91.186403
...                  ...
18534          49.539793
18535          51.404000
18536          54.341262
18537          44.125321
18538          48.886044

[18539 rows x 1 columns]

In [194]:
pip2_inp_df.head(5)

Predicted_ratings
0          88.444981
1          91.547345
2          90.695964
3          88.536642
4          91.186403

# Combining age with data frame created above

In [195]:
age=fifa_necc_num['Age']

In [196]:
age=pd.DataFrame(age)

In [197]:
type(age)

pandas.core.frame.DataFrame

In [198]:
age.head(5)

Age
0   35
1   34
2   33
3   31
4   23

In [199]:
frames = [age, pip2_inp_df]

result = pd.concat(frames,axis=1)

In [200]:
result.head(5)

Age  Predicted_ratings
0   35          88.444981
1   34          91.547345
2   33          90.695964
3   31          88.536642
4   23          91.186403

# combining total stats with data frame

In [201]:
TotalStats=fifa_necc_num['TotalStats']

In [202]:
TotalStats=pd.DataFrame(TotalStats)

In [203]:
frames1 = [result, TotalStats]

result1 = pd.concat(frames1,axis=1)

In [204]:
result1

Age  Predicted_ratings  TotalStats
0       35          88.444981        2190
1       34          91.547345        2147
2       33          90.695964        2205
3       31          88.536642        2303
4       23          91.186403        2177
...    ...                ...         ...
18534   21          49.539793        1287
18535   17          51.404000        1289
18536   18          54.341262        1333
18537   17          44.125321        1113
18538   25          48.886044        1277

[18539 rows x 3 columns]

In [205]:
term=int(fifa["Contract Until"])-int(fifa["Joined On"])

TypeError: cannot convert the series to <class 'int'>

In [206]:
term=(fifa["Contract Until"].astype(int)).sub(fifa["Joined On"])

ValueError: invalid literal for int() with base 10: '-'

In [207]:
pip2_inp_df=result1
len(pip2_inp_df)

18539

In [208]:
result

Age  Predicted_ratings
0       35          88.444981
1       34          91.547345
2       33          90.695964
3       31          88.536642
4       23          91.186403
...    ...                ...
18534   21          49.539793
18535   17          51.404000
18536   18          54.341262
18537   17          44.125321
18538   25          48.886044

[18539 rows x 2 columns]

In [209]:
len(actual_value)

18539

# Train Test combined data frame for Wage prediction

In [210]:
train_x, test_x, train_y_V, test_y_V = train_test_split(pip2_inp_df, actual_value, test_size=0.3)

In [211]:
train_x.head(5)

Age  Predicted_ratings  TotalStats
9214    30          65.596508        1831
17257   25          56.503650        1493
14367   30          61.650191        1618
14334   24          62.746192        1650
9359    35          69.288175        1782

In [212]:
len(test_y_V)

5562

In [213]:

from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score


model = LinearRegression()
model.fit(train_x, train_y_V)
pred_W = model.predict(test_x)


pred_W[:5]


array([-198484.37577543, 6556849.79093521, 1200918.86568405,
       2072833.7278079 , 4191466.3947135 ])

In [214]:
print(sm.mean_absolute_error(test_y_V, pred_W))


3157307.9926469857


In [215]:
test_y_V[:5]

12547     425000
1562     5500000
12660     600000
12284     925000
6024     1500000
Name: Value(in Euro), dtype: int64

In [216]:
train_y_V[:5]

9214     825000
17257    180000
14367    325000
14334    525000
9359     275000
Name: Value(in Euro), dtype: int64

In [217]:
test_x[:5]

Age  Predicted_ratings  TotalStats
12547   29          64.369745        1745
1562    30          73.246537        1893
12660   26          64.218066        1535
12284   23          63.237629        1013
6024    26          67.992422        1766